Add remediations page
RedHatInsights/in-place-upgrades-frontend pull request #183
Opened 2024-02-09 10:35 UTC by Monnte

**OAMG-9902**

Added page for remediations.
Table with available remediation with some metadata and link to them, introduced in this PR.

Additional filtering for leapp remediations playbooks will be needed (another task).

- [x] PR has a short description
- [x] Tests for the changes have been added

2024-02-16 15:44 UTC, andywaltlova requested changes
Mostly just typo commentc, otherwise LGTM, created two other issues in repo based on the testing I did, feel free to comment on them.

2024-02-16 15:44 UTC, andywaltlova commented on src/Helpers/constants.ts
> +export const REMMEDIATIONS_DETAIL_ROOT = '/insights/remediations';
```suggestion
export const REMEDIATIONS_DETAIL_ROOT = '/insights/remediations';
```

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/__tests__/RemediationsPage.test.js
> +  it('should render table with recommendations', async () => {
Shouldn't this whole file use the remediation word isntead of recommendation? I assume it was just copied from recommendations :sweat_smile:

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +  const [remmediations, setRemediations] = React.useState<Remediation[]>([]);
```suggestion
  const [remediations, setRemediations] = React.useState<Remediation[]>([]);
```

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +            {remmediations.length === 0 ? (
```suggestion
            {remediations.length === 0 ? (
```

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +              remmediations.map((rec, rowIndex) => (
```suggestion
              remediations.map((rec, rowIndex) => (
```

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +                    <a key={rec.id} href={`${REMMEDIATIONS_DETAIL_ROOT}/${rec.id}`} target="_blank" rel="noreferrer">
```suggestion
                    <a key={rec.id} href={`${REMEDIATIONS_DETAIL_ROOT}/${rec.id}`} target="_blank" rel="noreferrer">
```

2024-02-16 15:44 UTC, andywaltlova commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +                  </Bullseye>
Little bit prefer what actual remediations have, it's more informative

![image](https://github.com/RedHatInsights/in-place-upgrades-frontend/assets/19702477/3e12ae8d-a24f-4848-ba5a-3d7d2d55fefe)

2024-02-20 13:38 UTC, Monnte commented on src/Components/RemediationsPage/RemediationsTable.tsx
> +    return count;
Yep, we don't need that return value.

2024-02-26 13:05 UTC, andywaltlova approved these changes

2024-02-26 13:05 UTC, merged