Patternfly5
RedHatInsights/in-place-upgrades-frontend pull request #78
Opened 2023-09-13 12:24 UTC by Monnte

**OAMG-9790**

TBD

2023-09-14 08:01 UTC, andywaltlova requested changes
Looks good, just one question :+1:

2023-09-14 08:01 UTC, andywaltlova commented on package.json
I was looking at the guide and they recommended using babel only for tests (if we don't have them for typescript), could we remove these dev dependencies? (I tried it and it seems to work)

I removed the dependencies and changed the config to:
```
module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript'],
};
```
- babel/plugin-proposal-object-rest-spread
- babel/plugin-transform-runtime
- babel-plugin-transform-imports  (maybe related to this is the disabled rule for eslint `rulesdir/forbid-pf-relative-imports` - I did not get what is its purpose before, but maybe it is because of speed and load?)

test run fine and build also works :shrug:  (warnings after compile look same as before)

2023-09-15 08:39 UTC, Monnte commented on package.json
I am okay with that, if it only affects tests time a little bit :+1:

2023-09-15 09:01 UTC, andywaltlova approved these changes

2023-09-15 09:01 UTC, merged